#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hours=0
minutes=1
while [ $hours -le 12 ]
do
while [ $minutes -le 59 ]
do
echo "$hours:$minutes"
minutes=$((minutes+1))
done
hours=$((hours+1))
minutes=0
done | head -70
